"""initial_schema_35_tables

Revision ID: 3911ed6c22f7
Revises: 
Create Date: 2026-06-06 21:15:54.478416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '3911ed6c22f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('chatbot_status', sa.Enum('NORMAL', 'SAFE_MODE', 'DISABLED', name='chatbot_status'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('admin_activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'PUBLISHED', 'RESTORED', 'OVERRIDDEN', 'ENABLED', 'DISABLED', 'INVITED', 'REVOKED', 'LOGIN', 'FAILED_LOGIN', 'SECRET_ROTATED', name='admin_action_type'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_activity_logs_action_type'), 'admin_activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_brand_id'), 'admin_activity_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_created_at'), 'admin_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_id'), 'admin_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_user_id'), 'admin_activity_logs', ['user_id'], unique=False)
    op.create_table('brand_configs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('response_length', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='response_length'), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('rag_similarity_threshold', sa.Float(), nullable=True),
    sa.Column('recommendation_top_n', sa.Integer(), nullable=True),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('greeting_message', sa.Text(), nullable=True),
    sa.Column('signoff_message', sa.Text(), nullable=True),
    sa.Column('fallback_message', sa.Text(), nullable=True),
    sa.Column('fallback_tone_profile', sa.Text(), nullable=True),
    sa.Column('no_medical_claims', sa.Boolean(), nullable=True),
    sa.Column('no_over_explaining', sa.Boolean(), nullable=True),
    sa.Column('no_aggressive_upselling', sa.Boolean(), nullable=True),
    sa.Column('no_unnecessary_details', sa.Boolean(), nullable=True),
    sa.Column('no_medical_tone', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_per_user', sa.Integer(), nullable=True),
    sa.Column('conversation_retention_days', sa.Integer(), nullable=True),
    sa.Column('lead_capture_trigger', sa.Enum('ON_WELCOME', 'AFTER_N_MESSAGES', 'ON_INTENT', 'MANUAL', name='capture_trigger'), nullable=True),
    sa.Column('lead_capture_n_messages', sa.Integer(), nullable=True),
    sa.Column('lead_show_phone_field', sa.Boolean(), nullable=True),
    sa.Column('lead_gdpr_consent_text', sa.Text(), nullable=True),
    sa.Column('lead_allow_skip', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    op.create_index(op.f('ix_brand_configs_id'), 'brand_configs', ['id'], unique=False)
    op.create_table('brand_image_styles',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('image_style_profile', sa.Enum('SOFT_LUXURY', 'CLINICAL_LUXURY', 'K_BEAUTY_MINIMAL', 'BOTANICAL', 'MODERN_CLEAN', 'CUSTOM', name='image_style_profile'), nullable=True),
    sa.Column('product_card_edges', sa.Enum('ROUNDED', 'SHARP', name='card_edges'), nullable=True),
    sa.Column('product_card_background_color', sa.String(length=7), nullable=True),
    sa.Column('product_card_overlay_style', sa.Enum('NONE', 'GRADIENT', 'SHADOW', name='overlay_style'), nullable=True),
    sa.Column('routine_card_edges', sa.Enum('ROUNDED', 'SHARP', name='card_edges'), nullable=True),
    sa.Column('routine_card_background_color', sa.String(length=7), nullable=True),
    sa.Column('routine_card_overlay_style', sa.Enum('NONE', 'GRADIENT', 'SHADOW', name='overlay_style'), nullable=True),
    sa.Column('ui_button_style', sa.Enum('ROUNDED', 'SHARP', name='card_edges'), nullable=True),
    sa.Column('ui_button_color', sa.String(length=7), nullable=True),
    sa.Column('ui_card_background', sa.String(length=7), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    op.create_index(op.f('ix_brand_image_styles_id'), 'brand_image_styles', ['id'], unique=False)
    op.create_table('compliance_rules',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('BLOCKED_PHRASE', 'ALLOWED_PHRASE', 'BLOCKED_TOPIC', 'CONVERSATION_BOUNDARY', name='compliance_rule_type'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_brand_id'), 'compliance_rules', ['brand_id'], unique=False)
    op.create_index(op.f('ix_compliance_rules_id'), 'compliance_rules', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_rules_is_active'), 'compliance_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_compliance_rules_rule_type'), 'compliance_rules', ['rule_type'], unique=False)
    op.create_table('conversations',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('WEBSITE', 'WHATSAPP', 'INSTAGRAM', name='channel_type'), nullable=False),
    sa.Column('user_identifier', sa.Text(), nullable=True),
    sa.Column('session_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('current_handler', sa.Enum('AI', 'HUMAN', name='conversation_handler'), nullable=True),
    sa.Column('is_escalated', sa.Boolean(), nullable=True),
    sa.Column('escalation_status', sa.Enum('WAITING', 'IN_PROGRESS', 'RESOLVED', name='escalation_status'), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_brand_id'), 'conversations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_conversations_channel'), 'conversations', ['channel'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_is_flagged'), 'conversations', ['is_flagged'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=True)
    op.create_table('embedding_sync_status',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PRODUCT', 'FAQ', 'ROUTINE', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='embedding_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id')
    )
    op.create_index(op.f('ix_embedding_sync_status_brand_id'), 'embedding_sync_status', ['brand_id'], unique=False)
    op.create_index(op.f('ix_embedding_sync_status_id'), 'embedding_sync_status', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_sync_status_status'), 'embedding_sync_status', ['status'], unique=False)
    op.create_table('embeddings',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PRODUCT', 'FAQ', 'ROUTINE', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.String(), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_brand_id'), 'embeddings', ['brand_id'], unique=False)
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    op.create_table('error_logs',
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('WEBSITE', 'WHATSAPP', 'INSTAGRAM', name='channel_type'), nullable=True),
    sa.Column('error_type', sa.Enum('AI_API_FAILURE', 'EMBEDDINGS_API_FAILURE', 'STORAGE_FAILURE', 'TIMEOUT', 'WEBHOOK_FAILURE', name='error_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_brand_id'), 'error_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_id'), 'error_logs', ['id'], unique=False)
    op.create_table('faqs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_brand_id'), 'faqs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    op.create_index(op.f('ix_faqs_id'), 'faqs', ['id'], unique=False)
    op.create_table('ip_block_list',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('blocked_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', 'brand_id')
    )
    op.create_index(op.f('ix_ip_block_list_id'), 'ip_block_list', ['id'], unique=False)
    op.create_index(op.f('ix_ip_block_list_ip_address'), 'ip_block_list', ['ip_address'], unique=False)
    op.create_table('moderation_configs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('sensitivity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='moderation_sensitivity'), nullable=True),
    sa.Column('response_on_block', sa.Enum('SILENT_DROP', 'POLITE_REFUSAL', 'BRAND_FALLBACK', name='moderation_response'), nullable=True),
    sa.Column('allow_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('block_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_injection_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    op.create_index(op.f('ix_moderation_configs_id'), 'moderation_configs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('EMBEDDING_FAILED', 'REPEATED_ABUSE', 'AI_API_FAILURE', 'BRAND_STATUS_CHANGE', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('purchase_url', sa.Text(), nullable=True),
    sa.Column('is_in_stock', sa.Boolean(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_in_stock'), 'products', ['is_in_stock'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'version_number')
    )
    op.create_index(op.f('ix_prompt_versions_brand_id'), 'prompt_versions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_id'), 'prompt_versions', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_is_live'), 'prompt_versions', ['is_live'], unique=False)
    op.create_table('recommendation_rules',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('EXCLUSION', 'CONFLICT', 'PRIORITY', 'SUITABILITY', name='recommendation_rule_type'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_rules_brand_id'), 'recommendation_rules', ['brand_id'], unique=False)
    op.create_index(op.f('ix_recommendation_rules_id'), 'recommendation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_rules_rule_type'), 'recommendation_rules', ['rule_type'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('routines',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_skin_type', sa.Enum('OILY', 'DRY', 'COMBINATION', 'SENSITIVE', 'NORMAL', name='skin_type'), nullable=True),
    sa.Column('target_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_brand_id'), 'routines', ['brand_id'], unique=False)
    op.create_index(op.f('ix_routines_id'), 'routines', ['id'], unique=False)
    op.create_index(op.f('ix_routines_is_active'), 'routines', ['is_active'], unique=False)
    op.create_table('secrets',
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('secret_type', sa.Enum('ANTHROPIC_API_KEY', 'EMBEDDINGS_API_KEY', 'S3_CREDENTIALS', 'META_WHATSAPP_TOKEN', 'META_INSTAGRAM_TOKEN', 'WEBHOOK_SECRET', name='secret_type'), nullable=False),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=False),
    sa.Column('last_four_chars', sa.String(length=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'secret_type', name='uq_secrets_brand_type')
    )
    op.create_index(op.f('ix_secrets_brand_id'), 'secrets', ['brand_id'], unique=False)
    op.create_index(op.f('ix_secrets_id'), 'secrets', ['id'], unique=False)
    op.create_index(op.f('ix_secrets_secret_type'), 'secrets', ['secret_type'], unique=False)
    op.create_table('tone_settings',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('emotional_style', sa.Enum('WARM', 'CLINICAL', 'LUXURIOUS', 'FRIENDLY', name='emotional_style'), nullable=True),
    sa.Column('communication_style', sa.Enum('FORMAL', 'CASUAL', name='communication_style'), nullable=True),
    sa.Column('emoji_usage', sa.Boolean(), nullable=True),
    sa.Column('vocabulary_preferred', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary_avoided', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('softness_level', sa.Enum('GENTLE', 'NEUTRAL', 'DIRECT', name='softness_level'), nullable=True),
    sa.Column('sensory_language_enabled', sa.Boolean(), nullable=True),
    sa.Column('emotional_cues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('restricted_adjectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clinical_language_allowed', sa.Boolean(), nullable=True),
    sa.Column('harsh_word_blocking', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    op.create_index(op.f('ix_tone_settings_id'), 'tone_settings', ['id'], unique=False)
    op.create_table('user_block_list',
    sa.Column('user_identifier', sa.Text(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('blocked_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_identifier', 'brand_id')
    )
    op.create_index(op.f('ix_user_block_list_id'), 'user_block_list', ['id'], unique=False)
    op.create_index(op.f('ix_user_block_list_user_identifier'), 'user_block_list', ['user_identifier'], unique=False)
    op.create_table('user_brand_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'brand_id')
    )
    op.create_index(op.f('ix_user_brand_assignments_brand_id'), 'user_brand_assignments', ['brand_id'], unique=False)
    op.create_index(op.f('ix_user_brand_assignments_id'), 'user_brand_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_user_brand_assignments_user_id'), 'user_brand_assignments', ['user_id'], unique=False)
    op.create_table('api_usage_logs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('api_type', sa.Enum('CLAUDE', 'EMBEDDINGS', name='api_usage_type'), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_api_type'), 'api_usage_logs', ['api_type'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_brand_id'), 'api_usage_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_created_at'), 'api_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_id'), 'api_usage_logs', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('channel', sa.Enum('WEBSITE', 'WHATSAPP', 'INSTAGRAM', name='channel_type'), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'email_hash', name='uq_leads_brand_email')
    )
    op.create_index(op.f('ix_leads_brand_id'), 'leads', ['brand_id'], unique=False)
    op.create_index(op.f('ix_leads_channel'), 'leads', ['channel'], unique=False)
    op.create_index(op.f('ix_leads_email_hash'), 'leads', ['email_hash'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'AGENT', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('user_identifier', sa.Text(), nullable=True),
    sa.Column('blocked_input', sa.Text(), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'ABUSE', 'PROMPT_INJECTION', 'OFF_TOPIC', name='moderation_reason'), nullable=False),
    sa.Column('action_taken', sa.Enum('SILENT_DROP', 'POLITE_REFUSAL', 'BRAND_FALLBACK', name='moderation_response'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_brand_id'), 'moderation_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_created_at'), 'moderation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_logs_id'), 'moderation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_reason'), 'moderation_logs', ['reason'], unique=False)
    op.create_index(op.f('ix_moderation_logs_user_identifier'), 'moderation_logs', ['user_identifier'], unique=False)
    op.create_table('product_concerns',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('concern', sa.Enum('ACNE', 'AGING', 'HYDRATION', 'HYPERPIGMENTATION', 'SENSITIVITY', 'DULLNESS', name='skin_concern'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'concern')
    )
    op.create_index(op.f('ix_product_concerns_id'), 'product_concerns', ['id'], unique=False)
    op.create_index(op.f('ix_product_concerns_product_id'), 'product_concerns', ['product_id'], unique=False)
    op.create_table('product_skin_types',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('skin_type', sa.Enum('OILY', 'DRY', 'COMBINATION', 'SENSITIVE', 'NORMAL', name='skin_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'skin_type')
    )
    op.create_index(op.f('ix_product_skin_types_id'), 'product_skin_types', ['id'], unique=False)
    op.create_index(op.f('ix_product_skin_types_product_id'), 'product_skin_types', ['product_id'], unique=False)
    op.create_table('routine_steps',
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.Enum('CLEANSE', 'TONE', 'SERUM', 'TREAT', 'MOISTURIZE', 'SUNSCREEN', 'CUSTOM', name='routine_step_name'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'step_number')
    )
    op.create_index(op.f('ix_routine_steps_id'), 'routine_steps', ['id'], unique=False)
    op.create_index(op.f('ix_routine_steps_routine_id'), 'routine_steps', ['routine_id'], unique=False)
    op.create_table('widget_events',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widget_events_brand_id'), 'widget_events', ['brand_id'], unique=False)
    op.create_index(op.f('ix_widget_events_created_at'), 'widget_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_widget_events_event_type'), 'widget_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_widget_events_id'), 'widget_events', ['id'], unique=False)
    op.create_table('compliance_logs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('original_response', sa.Text(), nullable=False),
    sa.Column('replacement', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rule_triggered_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_triggered_id'], ['compliance_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_logs_brand_id'), 'compliance_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_compliance_logs_created_at'), 'compliance_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_logs_id'), 'compliance_logs', ['id'], unique=False)
    op.create_table('rag_retrieval_logs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('chunks_retrieved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunks_retrieved_count', sa.Integer(), nullable=True),
    sa.Column('top_similarity_score', sa.Float(), nullable=True),
    sa.Column('hit_threshold', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_retrieval_logs_brand_id'), 'rag_retrieval_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_created_at'), 'rag_retrieval_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_hit_threshold'), 'rag_retrieval_logs', ['hit_threshold'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_logs_id'), 'rag_retrieval_logs', ['id'], unique=False)
    op.create_table('recommendation_rule_logs',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('user_input_summary', sa.Text(), nullable=True),
    sa.Column('skin_type', sa.Enum('OILY', 'DRY', 'COMBINATION', 'SENSITIVE', 'NORMAL', name='skin_type'), nullable=True),
    sa.Column('concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('excluded_products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_count', sa.Integer(), nullable=True),
    sa.Column('applied_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_rule_logs_brand_id'), 'recommendation_rule_logs', ['brand_id'], unique=False)
    op.create_index(op.f('ix_recommendation_rule_logs_created_at'), 'recommendation_rule_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_rule_logs_id'), 'recommendation_rule_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_rule_logs_id'), table_name='recommendation_rule_logs')
    op.drop_index(op.f('ix_recommendation_rule_logs_created_at'), table_name='recommendation_rule_logs')
    op.drop_index(op.f('ix_recommendation_rule_logs_brand_id'), table_name='recommendation_rule_logs')
    op.drop_table('recommendation_rule_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_id'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_hit_threshold'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_created_at'), table_name='rag_retrieval_logs')
    op.drop_index(op.f('ix_rag_retrieval_logs_brand_id'), table_name='rag_retrieval_logs')
    op.drop_table('rag_retrieval_logs')
    op.drop_index(op.f('ix_compliance_logs_id'), table_name='compliance_logs')
    op.drop_index(op.f('ix_compliance_logs_created_at'), table_name='compliance_logs')
    op.drop_index(op.f('ix_compliance_logs_brand_id'), table_name='compliance_logs')
    op.drop_table('compliance_logs')
    op.drop_index(op.f('ix_widget_events_id'), table_name='widget_events')
    op.drop_index(op.f('ix_widget_events_event_type'), table_name='widget_events')
    op.drop_index(op.f('ix_widget_events_created_at'), table_name='widget_events')
    op.drop_index(op.f('ix_widget_events_brand_id'), table_name='widget_events')
    op.drop_table('widget_events')
    op.drop_index(op.f('ix_routine_steps_routine_id'), table_name='routine_steps')
    op.drop_index(op.f('ix_routine_steps_id'), table_name='routine_steps')
    op.drop_table('routine_steps')
    op.drop_index(op.f('ix_product_skin_types_product_id'), table_name='product_skin_types')
    op.drop_index(op.f('ix_product_skin_types_id'), table_name='product_skin_types')
    op.drop_table('product_skin_types')
    op.drop_index(op.f('ix_product_concerns_product_id'), table_name='product_concerns')
    op.drop_index(op.f('ix_product_concerns_id'), table_name='product_concerns')
    op.drop_table('product_concerns')
    op.drop_index(op.f('ix_moderation_logs_user_identifier'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_reason'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_created_at'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_brand_id'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email_hash'), table_name='leads')
    op.drop_index(op.f('ix_leads_channel'), table_name='leads')
    op.drop_index(op.f('ix_leads_brand_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_api_usage_logs_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_created_at'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_brand_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_api_type'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_index(op.f('ix_user_brand_assignments_user_id'), table_name='user_brand_assignments')
    op.drop_index(op.f('ix_user_brand_assignments_id'), table_name='user_brand_assignments')
    op.drop_index(op.f('ix_user_brand_assignments_brand_id'), table_name='user_brand_assignments')
    op.drop_table('user_brand_assignments')
    op.drop_index(op.f('ix_user_block_list_user_identifier'), table_name='user_block_list')
    op.drop_index(op.f('ix_user_block_list_id'), table_name='user_block_list')
    op.drop_table('user_block_list')
    op.drop_index(op.f('ix_tone_settings_id'), table_name='tone_settings')
    op.drop_table('tone_settings')
    op.drop_index(op.f('ix_secrets_secret_type'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_brand_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_routines_is_active'), table_name='routines')
    op.drop_index(op.f('ix_routines_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_brand_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_recommendation_rules_rule_type'), table_name='recommendation_rules')
    op.drop_index(op.f('ix_recommendation_rules_id'), table_name='recommendation_rules')
    op.drop_index(op.f('ix_recommendation_rules_brand_id'), table_name='recommendation_rules')
    op.drop_table('recommendation_rules')
    op.drop_index(op.f('ix_prompt_versions_is_live'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_brand_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_products_is_in_stock'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_moderation_configs_id'), table_name='moderation_configs')
    op.drop_table('moderation_configs')
    op.drop_index(op.f('ix_ip_block_list_ip_address'), table_name='ip_block_list')
    op.drop_index(op.f('ix_ip_block_list_id'), table_name='ip_block_list')
    op.drop_table('ip_block_list')
    op.drop_index(op.f('ix_faqs_id'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_brand_id'), table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_error_logs_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_brand_id'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_brand_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_embedding_sync_status_status'), table_name='embedding_sync_status')
    op.drop_index(op.f('ix_embedding_sync_status_id'), table_name='embedding_sync_status')
    op.drop_index(op.f('ix_embedding_sync_status_brand_id'), table_name='embedding_sync_status')
    op.drop_table('embedding_sync_status')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_flagged'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_brand_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_compliance_rules_rule_type'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_is_active'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_id'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_brand_id'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    op.drop_index(op.f('ix_brand_image_styles_id'), table_name='brand_image_styles')
    op.drop_table('brand_image_styles')
    op.drop_index(op.f('ix_brand_configs_id'), table_name='brand_configs')
    op.drop_table('brand_configs')
    op.drop_index(op.f('ix_admin_activity_logs_user_id'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_id'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_created_at'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_brand_id'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_action_type'), table_name='admin_activity_logs')
    op.drop_table('admin_activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
